version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15.2-jessie-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --production=true
      - run: yarn build

  test:
    docker:
      - image: circleci/node:10.15.2-jessie-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
